EXEC = glucose
DEPDIR    = mtl utils glucose-syrup/core satUtils
MROOT = $(PWD)/../..
COMP = g++
LFLAGS = -Wall -lpthread  -L/home/projects/11000744/matesoos/zlib-1.2.11


include $(MROOT)/mtl/template.mk
