EXEC = glucose
DEPDIR    = glucose-syrup/mtl glucose-syrup/utils glucose-syrup/core glucose-syrup/satUtils
MROOT = $(PWD)/../..
COMP = g++
LFLAGS = -Wall -lpthread  -L/home/projects/11000744/matesoos/zlib-1.2.11


include $(MROOT)/mtl/template.mk
