pipeline {
    agent any
    triggers {
        pollSCM('* * * * *')
    }
    stages {
        stage('perftest') {
            steps {
                dir('perftest') {
                    sh 'make'
                    sh 'make perftest-glucose_release'
                }
                sh 'perftest/perftest-glucose'
                sh 'perftest/perftest-glucose_release'
            }
        }
    }
}
