pipeline {
    agent any
    triggers {
        pollSCM('* * * * *')
    }
    stages {
        stage('test') {
            steps {
                dir('glucose-syrup/test') {
                    sh 'make'
                    sh './test-glucose'
                }
            }
        }
    }
}
