EXEC = glucose
DEPDIR    = mtl utils core satUtils
MROOT = $(PWD)/..
COMP = g++
CFLAGS= -std=c++11
LFLAGS = -Wall -lpthread  -L/home/projects/11000744/matesoos/zlib-1.2.11


include $(MROOT)/mtl/template.mk
